language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov-report term --cov=investpy tests/
# Add codecov
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash) 
