version: '3'

services:
  messagequeue:
    image: rabbitmq
    ports:
      - 5672:5672
    container_name: messagequeue
    logging:
      driver: none

  database:
    image: mongo
    ports:
      - 27017:27017
    container_name: database
    logging:
      driver: none

  server:
    image: server
    ports:
      - 7000:7000
    depends_on:
      - messagequeue
    volumes:
      - ./dockers/docker_data:/usr/src/app/data
    container_name: server

  api:
    image: api
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - ./dockers/docker_data:/usr/src/app/data
    container_name: api

  parser:
    image: parser
    depends_on:
      - messagequeue

    volumes:
      - ./dockers/docker_data:/usr/src/app/data
    container_name: parser

  saver:
    image: saver
    depends_on:
      - messagequeue
      - database
    container_name: saver
