version: '3'

services:
  pipeline-message-queue:
    image: rabbitmq
    ports:
      - 5672:5672
    container_name: pipeline-message-queue

  pipeline-database:
    image: mongo
    ports:
      - 27017:27017
    container_name: pipeline-database

  pipeline-server:
    image: server
    ports:
      - 7000:7000
    depends_on:
      - pipeline-message-queue
    volumes:
      - ./dockers/docker_data:/usr/src/app/data
    container_name: pipeline-server

  pipeline-api:
    image: api
    ports:
      - 8080:8080
    depends_on:
      - pipeline-database
    volumes:
      - ./dockers/docker_data:/usr/src/app/data
    container_name: pipeline-api

  pipeline-parser:
    image: parser

    depends_on:
      - pipeline-message-queue

    volumes:
      - ./dockers/docker_data:/usr/src/app/data
    container_name: pipeline-parser

  pipeline-saver:
    image: saver
    depends_on:
      - pipeline-message-queue
      - pipeline-database
    container_name: pipeline-saver