version: 3

services:
  server:
    build:
      ./server
    ports:
      - 8080:8080
    depends_on:
      - message-queue

  api:
    build:
      ./api
    depends_on:
      - database


  parser:
    build:
      ./parser
    depends_on:
      - message-queue


  saver:
    build:
      ./saver
    depends_on:
      - message-queue
      - database



  message-queue:
    image: rabbitmq
    ports:
      - 5672:5672

  database:
    image: mongo
    ports:
      - 27017:27017
